{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autosd-template.serviceAccountName" . }}
  labels:
    {{- include "autosd-template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
imagePullSecrets:
  - name: {{ .Values.image.name }}-registry-creds-app
