FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

LABEL name="${{values.component_id}}"
LABEL maintainer="${{values.owner}}"
LABEL description="${{values.description}}"

VOLUME ["/binaries"]
RUN mkdir -p /binaries


VOLUME ["/binaries"]