FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

LABEL name="${{values.component_id}}"
LABEL maintainer="${{values.owner}}"
LABEL description="${{values.description}}"

RUN mkdir -p /binaries

COPY .abi-ci.yml /binaries/.abi-ci.yml
#COPY binaries/img/ /binaries/img/

VOLUME ["/binaries"]