apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    argocd/app-selector: rht-gitops.com/janus-argocd=${{values.component_id}}-bootstrap
    backstage.io/kubernetes-id: ${{values.component_id}}
    janus-idp.io/tekton: ${{values.component_id}}
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: url:https://${{values.host}}/${{values.destination}}
    gitlab.com/project-slug: ${{values.destination}}
    quay.io/repository-slug: ${{values.registry_destination | dump}}
  tags:
    - automotive
    - rhivos
  links:
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.destination}}
      title: OpenShift DevSpaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
