{
 "title": "PCP Vector Checklist",
 "tags": [
  "pcp-vector",
  "pcp-checklist"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "performancecopilot-vector-datasource"
   },
   { "name": "url", "label": "URL" },
   { "name": "hostspec" }
  ]
 },
 "panels": [
  {
   "type": "performancecopilot-breadcrumbs-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "ASIL-B Sysbench",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "openmetrics.asil_sysbench.eps",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "QM Sysbench",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "openmetrics.qm_sysbench.eps",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "performancecopilot-troubleshooting-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - rate(kernel.percpu.cpu.idle)",
     "hostspec": "$hostspec",
     "legendFormat": "$instance",
     "url": "$url"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "performancecopilot-troubleshooting-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mem.util.available / mem.physmem",
     "hostspec": "$hostspec",
     "legendFormat": "$expr",
     "url": "$url"
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "performancecopilot-troubleshooting-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "disk.dev.avactive",
     "hostspec": "$hostspec",
     "legendFormat": "$instance",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     },
     "url": "$url"
    }
   ]
  },
  {
   "title": "Network RX Utilization",
   "type": "performancecopilot-troubleshooting-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(network.interface.in.bytes) / network.interface.baudrate",
     "hostspec": "$hostspec",
     "legendFormat": "$instance",
     "url": "$url"
    }
   ]
  },
  {
   "title": "Network TX Utilization",
   "type": "performancecopilot-troubleshooting-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(network.interface.out.bytes) / network.interface.baudrate",
     "hostspec": "$hostspec",
     "legendFormat": "$instance",
     "url": "$url"
    }
   ]
  }
 ]
}