ARG FEDORA_VERSION=39

FROM fedora:${FEDORA_VERSION}

RUN dnf install -y dnf-plugins-core \
    && dnf -y update \
    && dnf install -y python3-devel \
    && dnf clean all

COPY client.py /usr/bin/ffi-client
RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install psutil
CMD [ "ffi-client" ]
