ARG CONTAINER_BASE="fedora:39"

FROM $CONTAINER_BASE

RUN dnf install -y dnf-plugins-core \
    && dnf -y update \
    && dnf install -y python3-devel \
    && dnf clean all

EXPOSE 7001/tcp
COPY server.py /usr/bin/ffi-server
CMD [ "ffi-server" ]
